services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "3443:443"
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
